### ISSUE TITLE
Error Type: <type 'exceptions.AttributeError'>

### ISSUE THREAD

**Issue by meowmoo** [hyperion-project/hyperion.kodi#17]
21:59:44 T:140095424284416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'xbmc.RenderCapture' object has no attribute 'waitForCaptureStateChangeEvent'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.hyperion-master/addon.py", line 48, in <module>
                                                next_state = state.execute()
                                              File "/storage/.kodi/addons/script.service.hyperion-master/resources/lib/state.py", line 103, in execute
                                                self.__capture.waitForCaptureStateChangeEvent(200)
                                            AttributeError: 'xbmc.RenderCapture' object has no attribute 'waitForCaptureStateChangeEvent'
                                            -->End of Python script error report<--

**Comment by brindosch** [comment]
Fixed
