### ISSUE TITLE
addon does crash on start, log mentions protobuf [solved]

### ISSUE THREAD

**Issue by trampi** [hyperion-project/hyperion.kodi#41]
If you have the following error

```
19:27:57.645 T:140713844041472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Couldn't build proto file into descriptor pool!
                                            Invalid proto descriptor for file "message.proto":
                                              proto.ColorRequest.colorRequest: Message extensions cannot have required fields.
                                              proto.ImageRequest.imageRequest: Message extensions cannot have required fields.
                                              proto.ClearRequest.clearRequest: Message extensions cannot have required fields.
 
                                            Traceback (most recent call last):
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/addon.py", line 36, in <module>
                                                from state import DisconnectedState
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/resources/lib/state.py", line 27, in <module>
                                                from hyperion.Hyperion import Hyperion
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/resources/lib/hyperion/Hyperion.py", line 28, in <module>
                                                from message_pb2 import HyperionRequest
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/resources/lib/hyperion/message_pb2.py", line 14, in <module>
                                                serialized_pb='\n\rmessage.proto\x12\x05proto\"\x82\x01\n\x0fHyperionRequest\x12/\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x1e.proto.HyperionRequest.Command\"8\n\x07\x43ommand\x12\t\n\x05\x43OLOR\x10\x01\x12\t\n\x05IMAGE\x10\x02\x12\t\n\x05\x43LEAR\x10\x03\x12\x0c\n\x08\x43LEARALL\x10\x04*\x04\x08\n\x10\x65\"\x87\x01\n\x0c\x43olorRequest\x12\x10\n\x08priority\x18\x01 \x02(\x05\x12\x10\n\x08rgbColor\x18\x02 \x02(\x05\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x32\x41\n\x0c\x63olorRequest\x12\x16.proto.HyperionRequest\x18\n \x02(\x0b\x32\x13.proto.ColorRequest\"\xb1\x01\n\x0cImageRequest\x12\x10\n\x08priority\x18\x01 \x02(\x05\x12\x12\n\nimagewidth\x18\x02 \x02(\x05\x12\x13\n\x0bimageheight\x18\x03 \x02(\x05\x12\x11\n\timagedata\x18\x04 \x02(\x0c\x12\x10\n\x08\x64uration\x18\x05 \x01(\x05\x32\x41\n\x0cimageRequest\x12\x16.proto.HyperionRequest\x18\x0b \x02(\x0b\x32\x13.proto.ImageRequest\"c\n\x0c\x43learRequest\x12\x10\n\x08priority\x18\x01 \x02(\x05\x32\x41\n\x0c\x63learRequest\x12\x16.proto.HyperionRequest\x18\x0c \x02(\x0b\x32\x13.proto.ClearRequest\"/\n\rHyperionReply\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t')
                                              File "/home/trampi/.local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 878, in __new__
                                                return _message.default_pool.AddSerializedFile(serialized_pb)
                                            TypeError: Couldn't build proto file into descriptor pool!
                                            Invalid proto descriptor for file "message.proto":
                                              proto.ColorRequest.colorRequest: Message extensions cannot have required fields.
                                              proto.ImageRequest.imageRequest: Message extensions cannot have required fields.
                                              proto.ClearRequest.clearRequest: Message extensions cannot have required fields.
 
                                            -->End of Python script error report<--
19:28:06.799 T:140715759670464  NOTICE: CWebServer[8080]: Started
19:28:16.724 T:140715759670464  NOTICE: ES: Stopping event server with confirmation
19:28:17.408 T:140713555633920  NOTICE: ES: UDP Event server stopped
19:28:17.408 T:140713555633920  NOTICE: ES: Starting UDP Event server on port 9777
19:28:18.397 T:140715759670464   ERROR: JSONRPC Server: Failed to connect to sdpd
19:28:18.397 T:140713555633920  NOTICE: UDP: Listening on port 9777 (ipv6 : true)
19:29:03.833 T:140713824696064   ERROR: GetDirectory - Error getting
19:29:25.234 T:140712638260992   ERROR: Previous line repeats 9 times.
19:29:25.234 T:140712638260992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: A Message class can only inherit from Message
                                            Traceback (most recent call last):
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/addon.py", line 36, in <module>
                                                from state import DisconnectedState
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/resources/lib/state.py", line 27, in <module>
                                                from hyperion.Hyperion import Hyperion
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/resources/lib/hyperion/Hyperion.py", line 28, in <module>
                                                from message_pb2 import HyperionRequest
                                              File "/home/trampi/.kodi/addons/script.service.hyperion/resources/lib/hyperion/message_pb2.py", line 6, in <module>
                                                from google.protobuf import descriptor_pb2
                                              File "/home/trampi/.local/lib/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 1840, in <module>
                                                __module__ = 'google.protobuf.descriptor_pb2'
                                            TypeError: A Message class can only inherit from Message
                                            -->End of Python script error report<--
```

then reinstall protobuf via:

```
pip uninstall protobuf
pip install --no-binary=protobuf protobuf
```

can solve your problem.  
Happened under Kodi 18.2 and 17.x.  
A rollback of protobuf solved the problem. Documenting it here in case anyone else googles and doesn't find anything.

**Comment by papapep514** [comment]
...and on windows release??? any clue

**Comment by tpmodding** [comment]
why you use 3 question marks? Why are you so triggered? is there a personal problem?

**Comment by papapep514** [comment]
I guess Not resolved on Windows... And did not know that using 3 question marks means I am triggered...I am not, in any way.

**Comment by tpmodding** [comment]
ok good, but fyi: currently nobody is working on this addon anymore...

**Comment by krasatos** [comment]
So how can we install this addon for kodi on android? specifically fire tv stick
